# Generated by Django 4.0.4 on 2022-05-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoCode', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=255)),
                ('ordenJugadas', models.CharField(max_length=255)),
            ],
        ),
    ]
