# Generated by Django 4.0.4 on 2022-05-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_apertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sitio', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('partidaN', models.IntegerField()),
                ('humano', models.CharField(max_length=255)),
                ('maquina', models.CharField(max_length=255)),
                ('partidaR', models.CharField(max_length=10)),
                ('ganador', models.CharField(max_length=255)),
            ],
        ),
    ]
