# Generated by Django 4.0.4 on 2022-05-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=40)),
            ],
        ),
    ]
